# Generated by Django 3.1.4 on 2021-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('date_field', models.DateField()),
                ('Gender', models.BinaryField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
