# Generated by Django 3.1.4 on 2021-04-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
    ]
