# Generated by Django 3.1.4 on 2021-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_remove_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('date_field', models.DateField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
