# Generated by Django 3.1.4 on 2021-04-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_security_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='security_db',
            name='gender',
            field=models.CharField(default='Female', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Female', max_length=30),
        ),
    ]
