# Generated by Django 3.1.4 on 2021-04-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_appointments_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments_db',
            name='date_ofapp',
            field=models.DateTimeField(),
        ),
    ]
