# Generated by Django 3.1.7 on 2021-04-11 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_info_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='auth',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
