# Generated by Django 3.1.7 on 2021-04-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_role'),
    ]

    operations = [
         migrations.RenameModel("security", "securityt"),
         migrations.RenameModel("faculty", "facultyt")
    ]
