# Generated by Django 3.1.7 on 2021-04-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_visitort'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('doa', models.DateField()),
                ('timeIn', models.TimeField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('token', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
