# Generated by Django 3.1.7 on 2021-04-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210424_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='vname',
        ),
    ]
